export interface ContentBlock {
  type: "heading" | "subheading" | "paragraph" | "speaker" | "intro";
  text: string;
}

export interface ArticleData {
  id: string;
  slug: string;
  titleEN: string;
  titleZH: string;
  excerptEN: string;
  excerptZH: string;
  tagEN: string;
  tagZH: string;
  dateEN: string;
  dateZH: string;
  sourceEN?: string;
  sourceZH?: string;
  hueShift: number;
  hasContent: boolean;
  contentEN: ContentBlock[];
  contentZH: ContentBlock[];
}

export const articles: ArticleData[] = [
  {
    id: "will-wang-tianfan",
    slug: "will-wang-tianfan-solo-companies",
    titleEN: "Dialogue with BAI Capital Partner Will Wang: The Rise of Solo Companies and the Restructuring of VC Logic",
    titleZH: "对话 BAI 资本合伙人汪天凡：一人公司崛起与创投逻辑的重构",
    excerptEN: "BAI Capital Partner Will Wang shares insights on AI investment across four categories — media disruption, AI rollup, China advantage, and super human — and why the rise of solo companies is reshaping venture capital.",
    excerptZH: "BAI 资本合伙人汪天凡分享 AI 投资四大方向——媒体颠覆、AI 改造、中国优势、超级个体，以及一人公司崛起如何重塑创投逻辑。",
    tagEN: "Global Growth Insights",
    tagZH: "出海洞察",
    dateEN: "July 19, 2025",
    dateZH: "2025年7月19日",
    sourceEN: "From a conversation between Monica and Will Wang on July 19, 2025.",
    sourceZH: "内容来源于 2025 年 7 月 19 日，Monica 和 Will 汪天凡的对谈。",
    hueShift: 0,
    hasContent: true,
    contentEN: [
      { type: "intro", text: "BAI Capital: Since 2008, the BAI Capital team has invested in over 200 companies, achieving 18 IPOs and more than 40 unicorns. Their investment focus includes the internationalization of Chinese industries, leveraging advantages in technology, talent, and supply chains to drive breakthroughs in retail, fintech, content innovation, Web3, and more. BAI Capital's predecessor was Bertelsmann Asia Investments, part of the Bertelsmann Group — an international media, services, and education giant with nearly 200 years of history, operations in 50 countries, and approximately 80,000 employees." },
      { type: "heading", text: "Thirteen Years of Investing — What Stages Have You Gone Through?" },
      { type: "speaker", text: "Will Wang:" },
      { type: "paragraph", text: "Our fund started in 2008, and my investment career began in 2012. The first phase was mobile internet — we're application investors by origin. Back then, the apps included KEEP, Tantan, and other mobile internet applications — dating, communities — they became subscription or e-commerce business models. That was basically the first wave of mobile internet." },
      { type: "paragraph", text: "Later, there was a wave of industrial internet companies — B2B commerce. Then came the so-called sharing economy, like Mobike. We had Hellobike, which we invested in during that era." },
      { type: "paragraph", text: "After that, everyone started chasing the last tail of e-commerce — for example, Dingdong Maicai and the fresh grocery wave. After that ended, around 2020, everyone started investing in consumer brands. One of our best-performing companies is BOP, which does oral care — mouth sprays, toothpaste. It's probably number one on Douyin now, with excellent growth and operations." },
      { type: "paragraph", text: "Then for a while we were involved in blockchain-related things. Web3 was hot for a while, then it crashed. We entered the industry after Web3 had its problems — we thought it was a very cyclical industry. But through Web3's rise, when we looked at what was actually worth studying behind it, we saw blockchain acceleration, global de-SWIFTification, and many people wanting to bypass VISA — that's the stablecoin trend everyone's watching now. We actually started investing in some players and companies two or three years ago. We even set up a fund overseas to invest in European and American projects, because a lot of deregulation in this space started in the West." },
      { type: "paragraph", text: "Then starting two years ago, we looked at AI — specifically this wave of Transformer-based AI. We didn't invest in the 'Six Little Dragons.' Our investments are basically all application companies, many of which we just started investing in over the past six months. We've probably issued six or seven term sheets in the past two months, with many projects in the process of closing — all application-focused." },
      { type: "paragraph", text: "Beyond my personal track record, our fund has two other major threads. One is what we call 'the Chinese American Dream' — since 2008. For example, we invested in Yiche and NIO founder Li Bin. Projects he was involved with — Uxin, Mobike — were all highly related to Li Bin. He was essentially co-founder or founder of these projects." },
      { type: "paragraph", text: "We also looked at things from the perspective of daily life — food, clothing, transportation. In between, we invested in some autonomous driving and enterprise SaaS, but I think our deepest insights come from fintech." },
      { type: "paragraph", text: "We look at business models globally and found a major trend: financial inclusion — letting people who previously couldn't access banking services get access. In this trend, we invested in fintech unicorns in Mexico, Asia, and Africa. So fintech is one of our main threads. The stablecoin work I mentioned is also an extension of fintech. So overall, BAI Capital's investments cover three areas: fintech, consumer, and AI." },
      { type: "heading", text: "What Triggered Your Focus on AI?" },
      { type: "speaker", text: "Monica:" },
      { type: "paragraph", text: "What first drew your attention to AI?" },
      { type: "speaker", text: "Will Wang:" },
      { type: "paragraph", text: "The first AI company I encountered in my career was probably Face++, back when I first joined the company in 2012-2013. Then autonomous driving was a wave. Before this Transformer wave, there were GAN-based generation companies — we invested in companies that generated fashion designs for others." },
      { type: "paragraph", text: "We really started engaging with Transformer AI around GPT-3 and GPT-4. Before GPT-3, many founders were already telling us that game script writing could use AI. Then GPT-3.5 plus ChatGPT was when everyone saw it." },
      { type: "paragraph", text: "So we really started diving deep during GPT-3.5, but we didn't start getting a real feel for applications until after DeepSeek." },
      { type: "heading", text: "AI Investment in Four Categories: Media Disruption, Industry Transformation, China Advantage, Super Human" },
      { type: "speaker", text: "Monica:" },
      { type: "paragraph", text: "What kind of projects have you invested in over the past two months?" },
      { type: "speaker", text: "Will Wang:" },
      { type: "paragraph", text: "I categorize our AI investments into four types." },
      { type: "paragraph", text: "The first is Media Disruption — primarily looking at text, audio, video, and 3D gaming from a media medium perspective. We've found that in China's video AI space, among the global top 5-6 apps, about three are made by Chinese or Chinese-origin teams. This is very different from the AI coding landscape." },
      { type: "paragraph", text: "The main reason is that many models have already reached SOTA, but user needs aren't SOTA — they're layered. In these areas where user needs don't chase SOTA but we've already reached it, we can bring down the entire cost structure and rapidly provide easily accessible services." },
      { type: "paragraph", text: "So many video generation tools aren't trying to produce Hollywood blockbusters — they generate short, fun content. Chinese-made products are extremely strong in this area." },
      { type: "paragraph", text: "In the video space, we invested in what we call a 'Cursor for Video.' We believe that among Adobe's 30+ million paying users worldwide — similar in number to the world's programmers — those users also need something like Cursor to save time. So we invested in what we call, in quotes, 'Cursor for Video.'" },
      { type: "paragraph", text: "In image and 3D communities, we already have portfolio companies including TensorArt and LibLib — image community platforms doing very well with massive overseas traffic. Then there's Meshy AI, founded by Hu Yuanming (original Taichi Engine founder), a text-to-3D platform for game developers. So from images to video to 3D assets, we've already invested across the board." },
      { type: "paragraph", text: "Why do I mention this first? Because it's closely related to Bertelsmann's business. Among Bertelsmann's $20 billion global portfolio, the largest segment is TV stations, streaming, and MCN. Second is publishing — Penguin Random House, the world's largest publisher. Third is BMG, the music rights company. The entire books-film-music industry will be impacted by AI — some parts disrupted, some enhanced." },
      { type: "paragraph", text: "The second theme is AI Rollup — the AI upgrade, transformation, and acceleration of traditional companies or existing internet businesses. Here we pursue network effects. If AI can strengthen businesses that already have network effects or two-sided platforms, that's very powerful. Most VC returns over the past 10-20 years have come from network effects." },
      { type: "paragraph", text: "The third theme is China Advantage. Two examples: consumer electronics — we invested in VITURE (AR glasses) and Looki (AI-enhanced outdoor cameras). We're watching categories that ship tens of millions of units annually — headphones, glasses, watches — and their AI transformation. Another category is the next-generation SHEIN based on China's flexible supply chain, where the backend speed and efficiency are enhanced but the frontend personalization is taken to the extreme." },
      { type: "paragraph", text: "The last direction — and what we'll discuss today — is Super Human. We believe solo unicorns will emerge and solo companies will be empowered. But more importantly, it's not about creating unicorns — it's that work methods will fundamentally change." },
      { type: "paragraph", text: "In this changing work paradigm, there will be many 'pick-and-shovel' businesses. If I truly want to run a company in a highly efficient, lean way — what do I need? Do I need a labor market? Hiring HR, PR, GR, admin? Can I get some of these basic white-collar functions from agents rather than people? So we invested in a company that empowers this trend." },
      { type: "paragraph", text: "To summarize in English: Media Disruption, AI Rollup, China Advantage, and Super Human. But if I had to pick just one word instead of four directions, I'd say AI is achieving ultimate personalization — similar to how collaborative filtering algorithms personalized media through recommendation engines like Douyin. We still believe that in media, communities, two-sided platforms, and even basic information transmission, there will be radical personalization transformations." },
      { type: "heading", text: "The Investment Logic Behind Solo Companies" },
      { type: "speaker", text: "Monica:" },
      { type: "paragraph", text: "What stage are most of these AI companies you've invested in, and what's their scale?" },
      { type: "speaker", text: "Will Wang:" },
      { type: "paragraph", text: "We have angel-round companies valued at around $10 million, some even smaller. Then growth-stage companies valued at $200-300 million. Our individual investment amounts range from as small as $1.5 million to as large as $20-30 million." },
      { type: "speaker", text: "Monica:" },
      { type: "paragraph", text: "What about the Super Human / solo company space?" },
      { type: "speaker", text: "Will Wang:" },
      { type: "paragraph", text: "For solo companies and solo unicorn investments, we're still designing the amount and proportion, because there's a fundamental question: invest too little and it's meaningless — you might as well give them operational resources. Invest too much and the money doesn't really help them." },
      { type: "paragraph", text: "We think there will be a new investment instrument — similar to how General Catalyst invested in Grammarly's last round. It might be investing in your growth. You need money for growth, and I'll support you. This could be something like RBF (Revenue-Based Financing) — investing in the calculable ROI portion of your revenue growth, then sharing in the returns rather than taking equity." },
      { type: "paragraph", text: "Pre-PMF products in the solo unicorn stage should just use cloud providers for support — covering basic development costs. I think as long as someone can afford McDonald's every day to feed themselves, they should be able to use Cursor to write code and build things." },
      { type: "paragraph", text: "So before the product is ready, I think there should be a period of public resource support — maybe incubators or accelerators. Once the product is ready for promotion and scaling, that's when you need financial products and services. But is it still VC? I think the VC investment model — the amounts, closing process, complexity — even simplified, isn't really suitable for solo companies." },
      { type: "heading", text: "Will Solo Companies Kill VC?" },
      { type: "speaker", text: "Monica:" },
      { type: "paragraph", text: "The investment model for solo companies still seems like a question mark." },
      { type: "speaker", text: "Will Wang:" },
      { type: "paragraph", text: "Right. My vision is that solo companies are a good thing — they maximize an individual's leverage and returns. You're just one person, you don't split with anyone, so from a distribution perspective it's maximized. If your capabilities are also amplified, your returns are maximized too." },
      { type: "paragraph", text: "So VC has no role here. If an individual makes an AI product — like Cal AI, the calorie counting app — and earns several million dollars, who do they split with? They don't need to. They don't need investment. That's great for them." },
      { type: "paragraph", text: "But you might say capitalism doesn't seem to play a role here. I think it's like having a Douyin account that does well — you can earn millions too. If we assume that Xiaohongshu follower count equals monthly income — 10,000 followers means 10,000 RMB per month, 1 million followers means about 10 million RMB per year, roughly $1.5 million. Why would you split with a VC?" },
      { type: "paragraph", text: "This fundamentally changes production relations because productive forces have been massively unleashed. You don't need to be employed by others, and you don't need to employ others. You participate in social collaboration, using platform resources on open platforms to achieve personal financial growth. That's a great thing." },
      { type: "speaker", text: "Monica:" },
      { type: "paragraph", text: "Will solo companies kill VC?" },
      { type: "speaker", text: "Will Wang:" },
      { type: "paragraph", text: "No, because human-to-human collaboration can't be eliminated just because AI amplifies individual capabilities. Today's interview has to happen between you and me, right? If a machine conducted this interview, the content probably wouldn't be something listeners would want to hear." },
      { type: "paragraph", text: "Human-to-human collaboration will remain very important — even more important. When your individual impact is amplified through AI, it's still a linear relationship. The non-linear growth that capital seeks must come from collaboration." },
      { type: "paragraph", text: "A solo company's capabilities mainly come from their creativity and their extraordinary mental fortitude and execution. But they have a ceiling — their personal time — and a clear risk — they're alone." },
      { type: "paragraph", text: "So from a VC perspective, we want to invest in teams. If these highly capable solo founders can team up — even just two people creates a squared relationship, three people creates a cubed relationship. The exponential growth from three people multiplied together is the source of returns we're seeking — that's non-linear growth." },
      { type: "speaker", text: "Monica:" },
      { type: "paragraph", text: "What's the most perfect combination of three people?" },
      { type: "speaker", text: "Will Wang:" },
      { type: "paragraph", text: "A team like Manus — three people from different backgrounds, each with their own strong suits, all with strong execution and hands-on ability. Together they can build a product that, in an era where everyone's talking about the model bulldozer pushing from behind, can actually run faster than the model. I think that's very typical." },
      { type: "speaker", text: "Monica:" },
      { type: "paragraph", text: "What's the biggest threshold or challenge for solo companies? Product level, market level, technical level, or the human level?" },
      { type: "speaker", text: "Will Wang:" },
      { type: "paragraph", text: "It's actually very interesting. For product-focused solo companies, you're working for users, working for yourself — not for a boss. So the biggest challenge is this state change: I have to work for myself. People who work for themselves need strong mental fortitude." },
      { type: "paragraph", text: "You need powerful mental strength to constantly battle with Cursor — it's not a perfect tool. You have to keep iterating, overturning your previous work, setting your own work plans, releasing products with rhythm, setting your own deadlines, and using different tools. You don't know things, so you have to learn — and your learning time in this state far exceeds what it was at a big company." },
      { type: "paragraph", text: "That's why we want to build the Vibecorn community. People need to come out and share. People are lonely. The hardest part is that nobody's cracking the whip behind you — isn't it easy to give up? I think the psychological aspect of working alone is really important." },
      { type: "heading", text: "Founder Spectrum: Ambitious Visionaries, Young Geniuses, Star Students, Ruthless Operators" },
      { type: "speaker", text: "Will Wang:" },
      { type: "paragraph", text: "Our classification goes like this: Ambitious Visionaries, Young Geniuses, Star Students, and Ruthless Operators. But being an Ambitious Visionary is the most essential, non-negotiable condition." },
      { type: "paragraph", text: "The other three multiply with it. You can be a Young Genius times an Ambitious Visionary — a Young Genius is someone who achieves beyond their age. A Ruthless Operator is someone who'll stop at nothing to achieve their goal — that's a neutral description. A Star Student is someone from a big company — a P-level from ByteDance, Stanford, etc." },
      { type: "paragraph", text: "Star Students are easy to invest in when everyone's lost. Young Geniuses are who you invest in when everyone's feeling adventurous. Ruthless Operators are hard for most funds to invest in because they easily challenge your moral bottom line or values on the surface." },
      { type: "paragraph", text: "But I believe the most important thing is being an Ambitious Visionary. If you're not ambitious, being a Young Genius alone isn't enough." },
      { type: "paragraph", text: "What is ambition? There are different manifestations. Some ambition looks like: 'I've already achieved financial freedom, but I want to go higher, do something bigger, so I'm temporarily giving up my comfortable lifestyle.' Another form: 'To accomplish something great, I've brought my social relationships, my credit, my best friends, my most respected people into my company as co-founders, asking them to sacrifice their work and lifestyle to start a business with me.' And there's a pure, passionate form: 'As an individual facing a social problem or business opportunity, I feel duty-bound — if I don't do this, I'll be angry, because this thing needs to happen and I didn't make it happen.' A founder with that kind of righteous anger." },
      { type: "heading", text: "Three Fundamental Beliefs: Intelligence, Collaboration, Open Source" },
      { type: "speaker", text: "Monica:" },
      { type: "paragraph", text: "You've previously mentioned three beliefs in AI investing: believing in large models, believing in young people, and believing in open source. But in reality, large model development has hit bottlenecks, young entrepreneurs' success rates remain very low, and open source faces commercialization challenges. Are these three beliefs too idealistic?" },
      { type: "speaker", text: "Will Wang:" },
      { type: "paragraph", text: "After that podcast, we already revised one — we changed 'believe in young people' because we got criticized heavily, mostly by older people, haha." },
      { type: "paragraph", text: "Based on first principles, our current fundamental laws are: believe in intelligence, believe in collaboration, and believe in open source." },
      { type: "paragraph", text: "Believing in intelligence essentially means: when you want to scale or grow your business, your first recourse should be the power of intelligence and productivity, not hiring another person. We think many applications are built ahead of intelligence, and when intelligence reaches a certain level, it lifts those applications up. Cursor wasn't built just now — it was built three years ago, before the models. When Anthropic's coding capabilities got strong, it lifted Cursor up." },
      { type: "paragraph", text: "We changed 'believe in young people' because we've since seen many cases of experienced people whose experience combined with AI produces incredible results. If they're young at heart, still learning fast, and mentally strong, their capabilities absolutely exceed those of young people." },
      { type: "paragraph", text: "Believing in collaboration means: how do you acquire resources? Some say through internal company growth. We believe the solo company ideology means acquiring resources through industry-wide collaboration. If our community enables 1,000 solo companies to gather, surely some of them can collaborate as upstream and downstream partners?" },
      { type: "paragraph", text: "We emphasize collaboration between solo companies — we think this will be very powerful. We don't think a solo company should always be just one person. Collaboration between them — one plus one is definitely greater than two, maybe even greater than ten." },
      { type: "paragraph", text: "Believing in open source: people always think of open source as giving back or contributing, but it's not. Open source means remembering that accumulation and success are often built on the shoulders of those who came before." },
      { type: "paragraph", text: "Take the blockchain industry as an example. Most VC-invested companies have no technical contribution — they're essentially marketing companies. But why does the industry keep advancing technically? Ethereum, Layer 2, rollups — much of this isn't done by people in companies. It's done by open-source developers who work during the day and tinker with crypto at night. The entire blockchain industry is essentially the monetization of an open-source ecosystem." },
      { type: "paragraph", text: "The Ethereum Foundation is a group of only 200-300 people maintaining a $300-400 billion economic system. Including applications built on top, it's probably a $500-600 billion economy. Each person is maintaining roughly $1-2 billion worth of economic activity." },
      { type: "paragraph", text: "In AI, I believe there will also emerge a massive infrastructure and network contributed and maintained by open-source contributors. Without open source, if everyone has to rely on others' services in purely commercial relationships, I don't believe individuals or super intelligence can develop with peace of mind." },
      { type: "paragraph", text: "Based on these three fundamental laws — believe in intelligence, believe in collaboration, believe in open source — like the Taoist saying 'three begets all things,' many things will emerge from these principles." },
      { type: "heading", text: "Closing Thoughts" },
      { type: "speaker", text: "Monica:" },
      { type: "paragraph", text: "Thank you, Will, for this intellectual storm. When we step back from the details, we find this entire conversation has been about 'people.' From the necessity of 'Ambitious Visionaries' to the scarcity of 'mental fortitude,' from the leverage effect of solo unicorns to the exponential breakthroughs of teaming up — technology has unleashed productivity, but what truly defines the future is still humanity's challenge against its own limits." },
      { type: "paragraph", text: "That loneliness of 'nobody cracking the whip behind you' is perhaps the hidden cost of the rise of super individuals." },
      { type: "paragraph", text: "A final question for everyone: When AI easily makes us all 'Young Geniuses,' what posture will you choose to become an Ambitious Visionary? Share your thoughts in the comments. If you're interested in being a guest on our live stream, please leave us a message." },
    ],
    contentZH: [
      { type: "intro", text: "BAI 资本介绍：自 2008 年开始至今，BAI 资本团队累计投资超过 200 家企业，收获成员企业 18 个 IPO 和超过 40 家独角兽的成绩。投资领域上，重点关注中国产业的国际化拓展，发挥技术、人才和供应链的叠加优势，推动面向全球市场的中国企业和创业者在零售消费、金融科技、内容和媒介创新、Web3 及元宇宙探索等方向的突破性进展。同时立足中国市场的结构性转型窗口，在前沿科技及底层技术，新能源汽车与自动驾驶，软件服务驱动产业升级大趋势中抓住跨越周期大机会。BAI 资本的前身是贝塔斯曼集团旗下贝塔斯曼亚洲投资基金。贝塔斯曼是国际传媒、服务和教育巨头，有近 200 年历史，业务遍及全球 50 个国家，拥有约 8 万名员工，目标 2030 年实现气候中性。2021 年，BAI 资本团队进行独立募资，得到了来自国家主权基金、大型保险公司、互联网巨头和国际知名母基金等国际顶级机构 LP 的支持。" },
      { type: "heading", text: "十三年的投资生涯 经历过哪些阶段？" },
      { type: "speaker", text: "Will 汪天凡：" },
      { type: "paragraph", text: "基金，我们是从 08 年开始做的，然后我的投资生涯从 12 年开始，当时第一阶段是移动互联网，所以我们是投应用出身的人。当年的应用包括 KEEP、探探这些移动互联网应用，交友啊，社区啊，他们变成订阅的商业模式或者电商的商业模式，基本上第一波移动互联网。" },
      { type: "paragraph", text: "后来呢，又有一波产业互联网的公司，那 TOB 的可能当年做这个 TOB 的商贸的有一波 B2B，后来呢有一波所谓的共享经济，比如说摩拜，我们有哈啰 Bike，这些也是我们在那个时代投的。" },
      { type: "paragraph", text: "再后来大家开始抓这个电商的最后一个尾巴，比如说叮咚买菜，生鲜那一波啊。然后这个结束之后，到了 2020 年，大家开始投消费品牌。我们现在表现最好的有一家公司叫 BOP，它是一个做口腔护理，口喷牙膏，它应该是抖音现在第一名，增速和经营状态都非常不错。" },
      { type: "paragraph", text: "再之后呢，有一段时间我们在搞跟区块链相关的事情，那时候火了一阵子 WEB3，但后来掉下来了。掉下来之后我们是在 WEB3 出问题之后进入了这个行业，我们当时觉得这是一个很周期性的行业，但是我们通过 WEB3 的火了之后去看它背后到底什么东西值得去研究的时候，我们看到所谓区块链加速，全球的去 SWIFT 化。然后很多人想要去 VISA 等等这样的一个趋势，也是现在大家在看的什么稳定币那些东西，我们其实两三年前就开始投一些选手和公司，甚至我们还在国外成立了一个基金，也是为了去投欧美的项目，因为很多 deREGULATION 在这一块。这个监管的友好化是在欧美开始。" },
      { type: "paragraph", text: "再到两年前开始，我们看 AI，只是看这波 AI，就大模型 TRANSFORMER BASE AI。然后我们没有投六小龙，我们投的公司基本上都是应用公司，其实很多是这半年刚开始投的，我们大概过去的半年也出了可能六七张 TS 吧。过去两个月啊，然后密集的出了一些 OFFER，然后有很多项目都在交割，都是偏应用类的。当然我刚才说是我自己的履历，但我们基金很大一块，还有两个主线，一个是我们一直关注中国人的美国梦。从 08 年开始，那这个其实相当于就比如说我们当时投易车以及蔚来汽车创始人李斌，他当时经手过的项目包括优信啊，摩拜啊，其实都跟李斌高度相关的啊。其实相当于它是 COFOUNDER 或 FOUNDER OF 这些项目，以及我们当年投的确实涨得很好，后来股价一般，在那个时候从吃穿用度角度、出行角度去看这些东西。中间我们当然也投过一些自动驾驶，投过一些企业服务什么 SAAS，但我觉得我们心得最大的领域还是来自于 FINTECH。" },
      { type: "paragraph", text: "我们在全球啊，各地啊，去看商业模式，找到很大的一个趋势是 FINANCIAL INCLUSION。其实就是让很多原来不能接触银行服务的人能接触到银行服务。这个趋势里面我们投了墨西哥的一些金融独角兽企业，亚洲的，非洲的都有，所以 FINTECH 是我们一个主线。刚才说的稳定币也是因为 FINTECH 延伸的。所以回过头来讲，整个 BAI 资本的投资，三块，FINTECH，消费，然后 AI。" },
      { type: "heading", text: "最开始关注 AI 是个什么契机？" },
      { type: "speaker", text: "Monica：" },
      { type: "paragraph", text: "最开始关注 AI 是个什么契机？" },
      { type: "speaker", text: "Will 汪天凡：" },
      { type: "paragraph", text: "要说我职业生涯里见到第一家 AI 公司，可能算 FACE 加加，那是我刚进公司一二一三年的时候。然后中间自动驾驶是一波，再到后面，其实这个 TRANSFORMER BASE 之前这样干，GAN 生成的也有一些公司，我们投过去生成一些给别人做服装设计的公司。" },
      { type: "paragraph", text: "真正接触这波 TRANSFORMER AI 的其实在 GPT3、4 前后，主要是 GPT3 之前，已经有很多创始人在跟我们说，游戏的剧本的撰写都可以用到这些 AI 了。然后 3.5 加 CHATGPT 是让大家全部都看到的时候。" },
      { type: "paragraph", text: "所以我们真正开始沉下去研究，肯定是在 GPT3.5 的时候，但是真正开始看应用稍微有一点点感觉的时候，应该还是在 DEEPSEEK 之后。" },
      { type: "heading", text: "AI 投资四大类：媒体颠覆、产业改造、中国优势、一人公司" },
      { type: "speaker", text: "Monica：" },
      { type: "paragraph", text: "最近两个月出手的项目是什么样的？" },
      { type: "speaker", text: "Will 汪天凡：" },
      { type: "paragraph", text: "我把我们投的 AI 的项目分为四类啊。" },
      { type: "paragraph", text: "第一类呢，就是叫做 MEDIA DISRUPTION，这个媒体的颠覆。其实主要是跟文字，音频，视频，三维游戏这些从媒体介质角度去看。所以我们发现目前来讲中国的视频 AI 的领域在全球能够可能 TOP 五，TOP 六的 APP 里面可能有三个是中文或者华人做的。这个其实跟我们在 AI CODING 里面的局面很不一样啊。" },
      { type: "paragraph", text: "我觉得主要的原因就是有很多的模型我们已经追到 SOTA 了，但是用户的需求不是 SOTA 的，用户的需求是分层的，所以在这种领域，我们可以用户需求没有那么追求 SOTA。但是我们已经追到 SOTA 的情况下，我们把整个这个成本结构 COST DOWN 下来，迅速提供用户可以很容易获得的服务。" },
      { type: "paragraph", text: "所以你去看很多视频生成，没有说要生成好莱坞大片，都生成短的，好玩儿的啊。这块其实国人做的产品是非常强的。" },
      { type: "paragraph", text: "在视频领域，目前我们投了一个，我们把它叫做有点像 CURSOR FOR VIDEO。我们认为在 VIDEO 里面，全世界 ADOBE 的付费用户也有三千多万，程序员也有三千多万。我们认为 ADOBE 的三千多万的支付费用户也需要一个类似于像 CURSOR 帮你省时间，所以我们投了一个带引号的，叫做 CURSOR FOR VIDEO。就是在多模态里面，然后呢，在图片社区或者在三维社区里面，其实我们都已经有了 PORTFOLIO 包括 TENSOR ART，LIBLIB。大家都比较知晓的，就是图片社区这一类，我们有家公司做得不错啊，在海外的量非常大。然后另外就是 Meshy AI，是 HU YUANMING 做的，原来太极引擎的 FOUNDER HU YUANMING 做的一个文生 3D，或者说给游戏开发者和公司做的这个三维素材生成的一个平台，所以从图片到这个视频到三维素材我们其实都已经有所投资。" },
      { type: "paragraph", text: "为什么我先讲这个，是因为它跟我们贝塔斯曼的业务是很相关，因为贝塔斯曼在全球最主要的两百亿美金的构成里面最大的一块是电视台、流媒体 MCN。第二名是这个出版业务，企鹅兰登书屋，全世界最大出版社，第三是 BMG 版权音乐公司。所以书影音整套行业一定会被 AI 影响，你不能说颠覆，也许有些部分是颠覆，有些是影响，有些是加强。" },
      { type: "paragraph", text: "第二个点呢，我们主打的一个主题叫做 AI ROLLUP，这大家提的很多，就是传统公司或者现有的互联网业务的 AI 升级改造和加速，这里面我们追求的是网络效应，就是说，如果 AI 能够使本身就有网络效应或者双边平台的业务更加强的话，那个是很厉害的。因为大部分 VC 过去十几二十年所获得的回报收益大头都来自于网络效应。所以我们会投一些类似于跟比如随便说 KOL MATCHING 相关的一些平台，对吧，双边网络，就是这个对接人和商家，对接人和卖家或者怎么样的这样的一些些网络啊。我举个例子，还有一些可能跟线下的这个销售网络搭建有关的一些跟 AI 相关的事情。所以这个是叫做 AI ROLLUP。" },
      { type: "paragraph", text: "第三个主题呢，叫做 CHINA ADVANTAGE，就是中国优势。我举两个例子，一是消费电子，那这个在里面我们投了 VITURE，做 AR 眼镜的，它可能之后也很快会有一个 AI 的产品。另外呢，我们投了 Looki，一个做类似于户外相机的 AI 化，那这样的两家公司，我们也是差不多，应该是在最近，有一家是我们增持了很多。另一家也是最近又交割了新的一轮。这两个方向是跟消费电子的相关。那消费电子的其实大家看到很多，耳机，眼镜，手表，就是很多人都在看，所以我们也在看那些每年能够出货上亿上千万的品类的这个所谓的 AI 化的变化。还有一类基于中国供应链，比如说非常灵活的中国供应链所能诞生的，更新时代的 SHEIN，这个项目还不好说。那它更多的有点像就是说，如果 SHEIN 基于中国的供应链，能够把这个后端的速度效率给提升，但前端的个性化还没有做到极致，所以我们会投一家在全球电商里面可能把前端的个性化也做到极致的一个公司。所以这个叫做 CHINA ADVANTAGE。" },
      { type: "paragraph", text: "最后一个我们投的方向，今天我们也会讨论，叫做 SUPER HUMAN。我们认为一人独角兽会诞生，一人公司会被加强。但更重要的不是说要诞生独角兽或者什么样的公司，而是更重要的是工作方式会被改变。在这种工作方式改变下，会有很多卖水的人的生意，就是说，如果我真的想要以非常高效和 LEAN 的方式来做一家公司的话。我需要什么样的东西？我是不是需要一个劳动力市场？招我的 HR，招我的 PR，招我的 GR，招我的什么样的同事、员工？ADMIN、有一些基础的白领岗位，我可不可以从 AGENT 获取，而不是从人那儿获取？所以我们投了一家类似于来 EMPOWER 这样的一个趋势的公司。" },
      { type: "paragraph", text: "所以总结来讲就是，用英文说，就是叫是 MEDIA DISRUPTION、媒体颠覆，然后 AI ROLLUP、AI 对业务的改造，CHINA ADVANTAGE、中国的优势发挥，最后是 SUPER HUMAN、就是一人独角兽的诞生，这个是我们过去这两个月所看到的项目可被归的类。但我觉得呢，我比较喜欢拎出来的一个词儿是，我觉得 AI 确实正在做的一件事情是极致个性化。如果真的只要拎一个词儿，而不是四个方向，我们认为 AI 的极致个性化这件事情就和当年协同过滤算法对于这个媒体的这个个性化，什么大家看抖音啊、这些推荐算法引擎等等是一样的影响。我们仍然认为，在媒体，社区，双边平台，甚至最基础的信息传递领域，都会出现极致个性化的改造。" },
      { type: "heading", text: "一人公司的投资逻辑？" },
      { type: "speaker", text: "Monica：" },
      { type: "paragraph", text: "你投的这些 AI 的公司大部分是处于一种什么阶段，公司规模是怎么样的？" },
      { type: "speaker", text: "Will 汪天凡：" },
      { type: "paragraph", text: "我们有天使轮的公司，它的估值差不多在一千万美金左右，也有更小一些的，然后有成长期的公司的估值大概在两到三亿美金之间。我们单体的投资的金额基本上会从小到一百五十万美金，大到两千到三千万美金。" },
      { type: "speaker", text: "Monica：" },
      { type: "paragraph", text: "SUPER HUMAN 一人公司这个领域呢？" },
      { type: "speaker", text: "Will 汪天凡：" },
      { type: "paragraph", text: "单独的一人公司，一人独角兽的投资的金额和比例，我们还在设计，因为这就是一个问题，就是说你投少了对他来讲意义不大、还不如给他运营资源。投多了，其实钱对它的作用不大。所以我们认为这里面会有一种新的投资工具，就像就像 GENERAL CATALYST 投 GRAMMARLY 的最后那笔钱一样。他可能是一个投资于你增长的公司。你需要钱去做增长，我来帮你，我来支持你。所以这个里面可能有类似于国内大家会把它叫做 RBF，相当于 JIGUANTONG 那样的业务，投资于你可计算 ROI 的那部分收入增长，然后大家一起在这里面进行利益分配，而不是来占据你的股权。" },
      { type: "paragraph", text: "我觉得这里面有，支付部分，我觉得大家需要能够把关，它相当于如果你要收益分账的话，可能在支付的收款的部分，能够有一个双方都认可的一个记账的这个第三方嘛。然后和分账的第三方。第二呢是，大概率是需要一个做增长推广的运营团队或者公司，在这里面帮助这个团队做。这样的话大家也可以共同去理解这个事情的，因为你 ROI 是不错的话，那我投钱让你做这个增长，我才能觉得这个钱能回来啊。" },
      { type: "paragraph", text: "PRE PMF 的应该很难用这种方式投。我觉得 PRE PMF 的产品在一人独角兽阶段就就用云厂商来支持就好了，云厂商支持最基础的开发费用。我觉得一个人只要每天能吃麦当劳养活自己，我觉得就应该能用 CURSOR 写代码、做东西出来。所以我觉得在产品出来之前，我觉得应该有一段的时间考虑公共资源支持，可能也可以孵化器、加速器的角色也可以，那产品出来要推广了，再上一个新的台阶了，我觉得需要一些金融产品和服务。那还是不是 VC 啊？就是咱们刚才讨论到这个问题，我觉得 VC 的这个的投资模式，金额，交割方式，复杂程度还是，就算再简单，也不太适用于一人公司。" },
      { type: "heading", text: "一人公司是否会杀死 VC?" },
      { type: "speaker", text: "Monica：" },
      { type: "paragraph", text: "一人公司的这个投资模式现在感觉还是一个问号。" },
      { type: "speaker", text: "Will 汪天凡：" },
      { type: "paragraph", text: "对，我的设想是，一人公司呢，它是好事儿，它好在让一个人的这种能力的杠杆最大化，同时让它收益也能最大化。你就一个人嘛，那你确实没跟别人分，你确实在分配角度是最大化的，如果你能力也能放大，那你的收益也是最大化的。" },
      { type: "paragraph", text: "所以这里面 VC 的角色是没有的，就是他如果一个个人，他做一个产品 AI 产品，比如说那个 CAL AI，对吧，你说卡路里这个计算的 APP 你做得很好，你赚到可能你的收费有几百万美金，你跟谁去分呢？你没必要跟人分，那他也不需要投资，他就不需要投资了，那就是很好，对他来讲是好事儿。" },
      { type: "paragraph", text: "但是呢，你会说啊，那资本主义在这里面好像不发挥作用，对吧？对啊，我觉得这个不是这样。这个就相当于过去在抖音上有一个号，你做得很好，你也能有几百万收入。假设大家都说小红书的粉丝量等于小红书博主每个月的收入嘛，对吧？如果小红书你有一万粉，你每个月可以有一万块钱收入，那我就假设，如果你有一百万粉，那你就可能一年有个一千万收入，那就等于一百五十万美金了。你干嘛还要跟 VC 分钱呢？如果你能做到那样啊，这是很好的事情。这个本质上是是改变了生产关系，因为生产力极大地释放而改变了生产关系，也就意味着你不需要被别人雇用，你也不需要雇用别人。你通过参与社会协作，在公开平台上利用平台资源来实现个人的财务增长，大好事儿。" },
      { type: "speaker", text: "Monica：" },
      { type: "paragraph", text: "一人公司会杀死 VC 吗？" },
      { type: "speaker", text: "Will 汪天凡：" },
      { type: "paragraph", text: "不会啊，因为就是人和人之间的协作是无法因为 AI 放大到极致，人和人之间就不需要协作了。今天的访谈也必须在你我之间进行，对吧？如果有一个机器来访谈我们俩完成的那个内容，目前来讲应该还是做不到能够让其他的听众愿意听的。这里面不是说真假问题，我觉得将来技术可以做到，真到你也不知道是不是 AI 在仿，AI 在答的程度。但是我目前来讲，我觉得人好像似乎还是在追求某种体面。我还是希望我在听的是人在说的东西，而不是机器在说的东西，因为那东西不珍贵，不真实啊。" },
      { type: "paragraph", text: "人和人之间的协作还是会很重要，甚至更为重要。因为什么意思呢？当你自己个体的作用通过 AI 放大的时候，你还是一个线性关系。所谓的资本追求的增长也是追求非线性的。我们需要的非线性一定不来自于一个人在那儿努力干，因为它的时间有限，它的所有的增长一定来自于它用了什么工具。但是那些工具也都是大家有的，所以一人公司的能力主要来自于他的创意，和他自己的超强的心力和执行力。" },
      { type: "paragraph", text: "但是他毕竟是有一个上限，就是他自己个人的时间，且他有一个明确的风险，就是他一个人。所以呢，我们认为对于资本主义，对 VC 角度来讲，我们想要投的是个团队，所以如果这样的动手能力很强的一人公司或者 SOLO FOUNDER，能够组队组起来。他就算组两个人，他就是平方关系，三个人就是立方关系，这三个人乘起来的指数效应、指数增长是我们要追求的回报来源，那个是我们所说一个非线性增长的来源。" },
      { type: "speaker", text: "Monica：" },
      { type: "paragraph", text: "三个人最完美的搭配和组合是什么样的？" },
      { type: "speaker", text: "Will 汪天凡：" },
      { type: "paragraph", text: "就比如说像 MANUS 这样的团队，就是三个来自于不同背景的人，各自都有各自非常强的地方，执行力都很强，动手能力都非常强的人，合在一起才能做一个在当下大家都在讨论模型推土机，对吧？模型在后面推土，然后你在前面做应用，跑的还能比模型快的产品，我觉得这个是很典型。" },
      { type: "speaker", text: "Monica：" },
      { type: "paragraph", text: "一人公司最大的门槛或者是挑战是在什么层面？是产品层面，市场层面，技术层面，还是说人的层面？" },
      { type: "speaker", text: "Will 汪天凡：" },
      { type: "paragraph", text: "其实很有意思，我觉得人如何为自己工作，人如何为用户工作。我觉得一人公司大部分如果是做产品的公司啊，我们就说以产品公司为你，是在为用户工作，你在为自己工作，你没有在为别人，你没有在为老板工作。所以最大的挑战就是这种状态的改变，就是我要为自己工作。为自己工作的人需要有很强的心力。" },
      { type: "paragraph", text: "你拥有强大的心力，你要才能够不断地跟 CURSOR 搏斗啊。它也不是一个完美的工具，你要不断地改、迭代，推翻之前自己的东西，自己制定工作计划，有节奏的推出产品，自己给自己设 DEADLINE，然后有不同的工具调用。你不懂，你还要学，你学习的时间可能远大于你在这种状态下学习的时间远大于你在一个大公司工作时候的学习的时间，你要给自己安排学习的时间，你也得出得了门去跟别人交流，你也不能永远闭塞在家里。这是为什么我们想做 VIBECORN、一人独角兽社区的原因。" },
      { type: "paragraph", text: "大家是要出来分享的，大家是孤独的，所以最难的地方在于你也没有人在后面抽鞭子，你是不是也很容易放弃？我觉得一个人做事情心理还蛮重要的。" },
      { type: "speaker", text: "Monica：" },
      { type: "paragraph", text: "你在看一人公司的时候，怎么去评估这个创始人的心力？" },
      { type: "speaker", text: "Will 汪天凡：" },
      { type: "paragraph", text: "投资任何公司，对我们来说，最重要的是创始人的野心是否真的很大。大部分的 VC 包括我们，我觉得投很多的公司啊、项目，大家的成功概率甚至应该从大数上来讲不超过掷硬币不超过百分之五十。在这种情况下啊，去优化胜率，不如去优化赔率。作为投资人，我们现在感受到 AI 的发展非常快，我不可能去武断预测 AI 的发展，因为它有各种因素在扰动。我们的预测都是基于现象，要优化赔率、要投件大事儿，我们认为能够抓住的核心的因果、关系前提就是创始人自己野心得大，这个野心不是说他说出来，我要做一个什么万亿级别公司。" },
      { type: "paragraph", text: "什么叫野心？野心有体现这种方式对吧？有些野心是说我已经财务自由了，但是我要更上一层，我要再做一件大事，所以我暂时放弃我已经获得的一种非常好的生活状态和方式。还有种野心是我为了做成一件大事儿，我把我的社会关系，我的 CREDIT，我最好的朋友，我最尊敬的人一起带进了我的公司，成为创业伙伴，让他们牺牲他们的工作和生活方式、跟我一起来创业。我要一个很强的团队，这个很强的团队不是这帮人简历好，而从我这个创始人出发的最好的 NETWORK 已经被我拉进来了，这种野心的体现。" },
      { type: "paragraph", text: "还有一种野心的体现是这种很纯真的热爱，是说我作为一个个体，面对社会问题或者商业机会的时候，我发现责无旁贷、非我其谁，就是一定这个事情得我做，如果我不做，我会很生气，因为如果这件事情这么需要发生、但我没让它发生，而自带一种愤怒感的这种 FOUNDER。我至少看到过这三种人，我觉得这是我对于野心的粗浅理解。" },
      { type: "heading", text: "创始人光谱：野心家、小天才、好学生、大坏蛋" },
      { type: "speaker", text: "Will 汪天凡：" },
      { type: "paragraph", text: "我们的归类是这样，叫做野心家，小天才，好学生，大坏蛋这几类人，但是野心家是最必要的、不能舍去的条件。另外三个是相乘的关系，你可以是小天才，乘以野心家，小天才就是在你岁数不到的时候，做到了超越你岁数的事儿呗，就叫小天才。" },
      { type: "paragraph", text: "然后这个大坏蛋呢，是说他为了实现一件事情不择手段，没有底线，这是个中性描述。好学生就是大厂出来的，对吧？字节出来的 P 几啊，这个很好的学校啊，STANFORD 啊，这个就是叫做好学生。" },
      { type: "paragraph", text: "好学生是很容易在大家都很 LOST 的时候去投的人。小天才是大家很浪的时候会去投的人，因为好像我投完好学生，我觉得这些人太科班了，我再去投几个小天才，可能会有一些惊喜。然后其实九零后基金里面所有成的项目都不是小天才。大坏蛋是很多基金很难投到的人，因为它非常容易在表面上挑战你的道德底线，或者挑战你的价值观。大坏蛋往往是那种价值观跟我们不一样的人，他可能对外说一套，对内还做一套，但是他能把事情做成，太多这样的人，我们都可以举很多例子。但是我认为最重要的是野心家，如果你不是个野心家，你只是个小天才，也不行。" },
      { type: "heading", text: "三大信仰：相信智能、相信协作、相信开源" },
      { type: "speaker", text: "Monica：" },
      { type: "paragraph", text: "你在之前的播客里有提到 AI 投资的三大信仰：相信大模型，相信年轻人，相信开源。但是现实中呢，其实大模型的发展遇到了瓶颈，年轻人的创业成功的概率依然是很低的，开源也面临着商业化的困境。所以这三个信仰是不是太理想化了呢？" },
      { type: "speaker", text: "Will 汪天凡：" },
      { type: "paragraph", text: "首先我们那个播客录制之后就已经修正了一条，把相信年轻人改掉了，被骂死了，哈哈。大多是年纪大的人来骂我。我们后来自己基于第一性原理去想事儿。首先啊，我们现在的基本法是相信智能，相信协作和相信开源。" },
      { type: "paragraph", text: "来解释一下，相信模型、相信智能还是差不多的例子啊，我们的理解叫做，相信智能本质上是说，当你想要 SCALE 或者增长你的业务的时候，你首先诉诸的是智能的力量、生产力的来源，而不是诉诸于多雇一个人啊，这个是相信智能的意思，或者多做一些工程上的事儿、去弥补智能的不足。我们觉得很多应用是做在智能之前的，然后当智能的达到一定水平的时候，会把你这个应用给带起来。所以大家看到的 CURSOR 现在到这个水平，它也不是此刻才做的，三年前就已经做了，所以他是在模型之前做的。anthropic 模型能力强，CODING 能力强了之后，会把它一下子带起来啊。" },
      { type: "paragraph", text: "从大的角度来讲，如果你都不相信智能，你投什么 AI，或者你做什么 AI 呢？那你相信啥呢？你相信人，那相信人，那你就去回到之前的阿里巴巴时代的中共铁军、商业管理学啊。那你相信人的话，那你的组织。移动互联网时代结束，就 PC 互联网、移动互联网结束，大的公司的人口就是十几二十万嘛。那你相信人？你是不是要把自己做成富士康？你要变成一百万一千万？你相信人嘛，对吧？所以在组织层面其实相信智能，其实是在组织层面的一个第一的一条基本法。" },
      { type: "paragraph", text: "把相信年轻人改掉的原因，就是因为我们认为他甚至跟年轻、年长无关。因为我们后来又见到非常多的案例，是很有经验的人，他的经验和 AI 之间结合，看到一些苗头。所以我们认为确实就是，如果虽然年长，但是心态年轻，学习能力依旧强，心力十足，我觉得他们的发挥的能力绝对绝对比年轻人还要厉害。所以我们认为心态年轻很重要，但不是说要相信年轻人本身，所以会有很大的误解。" },
      { type: "paragraph", text: "后来我们觉得很重要的一个点，被我们遗漏的是相信协作。什么叫相信协作？我刚才第一条是讲组织，对吧？第二条就是说你怎么样去获得资源。有的人是说我获得资源来自于我公司内生，我们认为一人公司或者这种一人公司的意识形态是说，我获得资源的方式是跟全行业合作。那如果这个世界上因为我们的社区而实现一千个一人公司的聚会的话，这一千个里面总有你的上下游可以合作吧？我们强调的是一人公司之间的协作，我们认为这个会很强大，而且甚至里面暗含了一条暗线，我们希望这种协作能够让他们组队，就我们并不觉得一人公司本身就该永远是一个人，就这个一这个数字那么重要，不是的。我们认为协作，他们之间的协作一加一一定大于都不止二，可能一加一都大于十了，所以这个是协作。" },
      { type: "paragraph", text: "第三个，相信开源，相信开源的意义，它是一种，大家总把开源想成一种回馈或者贡献方式，其实不是，开源就是说一定要记住，很多时候事情的积累和成功是基于前人种树、后人乘凉的。" },
      { type: "paragraph", text: "我们拿区块链行业举个例子，区块链这个行业，大部分的 VC 投资公司是没有技术贡献，他们本质上都是营销公司，但是为什么这个行业从技术角度来讲还在不断地进步？大家在谈的什么以太坊，以太坊二层啊，ROLLUP 啊什么的一大堆事情，本质上很多时候不是在公司里的人做的。而是都是开源的开发者贡献都是大家白天在上班，晚上回去倒腾加密的这些事情贡献的。整个区块链行业，其实就是一个开源生态的变现，所以这个开源的生态非常了不起，没有人需要重复再做一条以太坊，但是你去以太坊上做出来的各种应用。在这些应用上面，他们还有很多是协议合约，你在上面再做应用，就这里面出来的那些力量，在过去的五年，我看的觉得非常的令人振奋。" },
      { type: "paragraph", text: "我觉得这里面导致的一个很有意思的结果就是以太坊基金会是一个只有两三百人的团体，他们在维系的是一个三千亿到四千亿美金体量的经济体。算上上面其他的应用，可能是五六千亿的经济体。所以你可以理解为每个人在维护接近一到两个 BILLION，就是十到二十亿美金体量的经济体。按照以太坊的 STAKING 的 REVENUE 来算的话，它十到二十亿美金一年都能贡献至少两三千万美金的这个计算的费用的收入，就相当于人均两三千万美金收入。" },
      { type: "paragraph", text: "我觉得在 AI 里面，一定还是会出现一个由开源贡献者贡献的，维护的一个巨大的基础设施和网络的。所以我觉得大家要对这个有信心，因为有了这个之后，协作和个体智能才能够发生啊。因为如果没有开源的话，所有人要基于他人的服务，大家的关系是一种商业利益的互相咬合的关系的话，我并不认为个体或者超级智能能够安心的发展。开源为什么如此重要，是在这儿。" },
      { type: "paragraph", text: "所以这个是我们认为，基于这三条基本法，我们说相信智能、相信协作、相信开源这三条基本法来工作的话。可以像道家一样的三生万物，就在这个基本法上，很多东西都会诞生。所以我们在做的那个社区就一个理念，我们不是一个 VC 要做一个东西，只是为了我们去宣传 VC 自己，不需要，我们想把相信这三条基本法的人都聚在一起。我们认为这三个东西乘起来会出来很多特别有意思的事情。这三件事情不是我们发明的，这个事情在区块链加密行业，在过去中本聪 08 年到现在，已经发生过了。" },
      { type: "speaker", text: "Monica：" },
      { type: "paragraph", text: "你刚才提到相信协作，能不能举一个能够产生于一加一大于十的类型？" },
      { type: "speaker", text: "Will 汪天凡：" },
      { type: "paragraph", text: "我举个例子，就是如果有一家一人公司，它在上游、它做的是电商，它卖货的，那是个卖货的公司，它需要找 KOL。另外一家一人公司是专门做 KOL 的一个一人 AGENT，这两个人就是可以协作的，你本质上其实相当于这个公司的这个产品销售组织和这个公司的营销推广啊，这个公司的产品供应链团队和一个公司的营销推广团队之间的合作。" },
      { type: "heading", text: "结语" },
      { type: "speaker", text: "Monica：" },
      { type: "paragraph", text: "感谢 Will 带来的这场思想风暴。当我们抽离细节，会发现这场对话始终在围绕「人」的层面。从「野心家」的必然性到「心力」的稀缺性，从一人独角兽的杠杆效应到组队的指数级突破——技术释放了生产力，但真正定义未来的，仍是人类对自我极限的挑战。" },
      { type: "paragraph", text: "那句「没有人在身后抽鞭子」的孤独感，或许正是超级个体崛起的隐秘代价。" },
      { type: "paragraph", text: "最后留给大家一个问题：当 AI 让我们轻易成为「小天才」，你愿以何种姿态成为野心家？欢迎在评论区分享思考。如果您有兴趣做客我们的直播，也请给我们留言。" },
    ],
  },
];

export function getArticleById(id: string): ArticleData | undefined {
  return articles.find((a) => a.id === id || a.slug === id);
}

export function getArticlesWithContent(): ArticleData[] {
  return articles.filter((a) => a.hasContent);
}
